apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-8y3s49
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-8y3s49
  namespace: my-nginx-8y3s49
  labels:
    name: nginx-8y3s49
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-8y3s49
  template:
    metadata:
      namespace: my-nginx-8y3s49
      labels:
        name: nginx-8y3s49
    spec:
      containers:
      - name: nginx-8y3s49
        image: nginx
        ports:
        - containerPort: 80

